"""ACTIVE-INSIGHTS.md auto-promote logic.

When a high-confidence insight is saved, auto-append to the agent's
ACTIVE-INSIGHTS.md so it's loaded at session startup (push, not pull).

Promote rules:
- user_correction: promote to ALL agent workspaces
- Other source_type + confidence >= 0.9: promote to saving agent only
- Other: no promote (Tier 2 only, pull via MCP)
"""

from pathlib import Path
from datetime import datetime

MAX_ENTRIES = 50
FILENAME = "ACTIVE-INSIGHTS.md"


def should_promote(source_type: str, confidence: float) -> bool:
    """判斷這條 insight 是否應該 promote 到 ACTIVE-INSIGHTS.md。"""
    if source_type == "user_correction":
        return True
    if confidence >= 0.9:
        return True
    return False


def get_target_workspaces(source_type: str, agent_id: str,
                          registry: dict) -> list[str]:
    """決定 promote 到哪些 workspace。"""
    if source_type == "user_correction":
        # 主人糾正 → 所有 agent workspace
        return [path for path in registry.values() if Path(path).exists()]
    else:
        # 其他高 confidence → 只給寫入者
        path = registry.get(agent_id)
        if path and Path(path).exists():
            return [path]
        return []


def format_entry(content: str, domain: str, source_type: str,
                 created_at: str, insight_id: str) -> str:
    """格式化一條 ACTIVE-INSIGHTS.md entry。"""
    return f"- [{domain}] {content}\n  _source: {source_type}, {created_at[:10]}, {insight_id}_\n"


def read_active_insights(workspace_path: str) -> list[str]:
    """讀取現有的 ACTIVE-INSIGHTS.md entries。"""
    filepath = Path(workspace_path) / FILENAME
    if not filepath.exists():
        return []

    entries = []
    current_entry = ""
    for line in filepath.read_text(encoding="utf-8").splitlines():
        if line.startswith("- ["):
            if current_entry:
                entries.append(current_entry)
            current_entry = line + "\n"
        elif line.startswith("  _source:") and current_entry:
            current_entry += line + "\n"
            entries.append(current_entry)
            current_entry = ""
        # skip header lines (<!-- comments --> and ## headers)

    if current_entry:
        entries.append(current_entry)

    return entries


def write_active_insights(workspace_path: str, entries: list[str]):
    """寫入 ACTIVE-INSIGHTS.md，含 header。"""
    filepath = Path(workspace_path) / FILENAME
    now = datetime.now().isoformat()

    header = (
        "<!-- AUTO-GENERATED by elsa-knowledge MCP server. Do not edit manually. -->\n"
        f"<!-- Last updated: {now} -->\n"
        f"<!-- Entries: {len(entries)} / {MAX_ENTRIES} max -->\n"
        "\n"
        "## 主人確認的行為規則\n"
        "\n"
    )

    filepath.write_text(header + "".join(entries), encoding="utf-8")


def promote_insight(content: str, domain: str, source_type: str,
                    confidence: float, agent_id: str, insight_id: str,
                    created_at: str, registry: dict) -> list[str]:
    """promote insight 到 ACTIVE-INSIGHTS.md。回傳受影響的 workspace 列表。"""

    if not should_promote(source_type, confidence):
        return []

    targets = get_target_workspaces(source_type, agent_id, registry)
    if not targets:
        return []

    new_entry = format_entry(content, domain, source_type, created_at, insight_id)
    affected = []

    for workspace_path in targets:
        entries = read_active_insights(workspace_path)

        # 檢查是否已有同 insight_id 的 entry（避免重複）
        if any(insight_id in e for e in entries):
            continue

        entries.append(new_entry)

        # 超過上限，淘汰最舊的（entries 順序 = 寫入順序 ≈ 時間順序）
        while len(entries) > MAX_ENTRIES:
            entries.pop(0)  # 移除最舊的

        write_active_insights(workspace_path, entries)
        affected.append(workspace_path)

    return affected


def update_insight_in_active(insight_id: str, new_content: str,
                              registry: dict) -> list[str]:
    """更新 ACTIVE-INSIGHTS.md 裡的 insight 內容。"""
    affected = []

    for agent_id, workspace_path in registry.items():
        filepath = Path(workspace_path) / FILENAME
        if not filepath.exists():
            continue

        text = filepath.read_text(encoding="utf-8")
        if insight_id not in text:
            continue

        # 找到包含 insight_id 的 entry，替換 content
        lines = text.splitlines()
        new_lines = []
        i = 0
        while i < len(lines):
            if lines[i].startswith("- [") and i + 1 < len(lines) and insight_id in lines[i + 1]:
                # 這是要更新的 entry，取 domain
                domain = lines[i].split("]")[0].replace("- [", "")
                source_info = lines[i + 1]  # 保留 source 行
                new_lines.append(f"- [{domain}] {new_content}")
                new_lines.append(source_info)
                i += 2
            else:
                new_lines.append(lines[i])
                i += 1

        filepath.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
        affected.append(workspace_path)

    return affected
